RS-185: Referral Register create and edit
Referral-System/referral-system-ui pull request #2
Opened 2022-09-12 15:34 UTC by umeixueiroBC

This adds the create an edit referral form to the project

2022-09-12 18:28 UTC, clopezh requested changes

2022-09-12 18:28 UTC, clopezh commented on src/components/button/Button.tsx
> +import {Link} from "react-router-dom";
```suggestion
import { Link } from "react-router-dom";
```

2022-09-12 18:28 UTC, clopezh commented on src/components/button/Button.tsx
> +          </Link>
indentation 🍹

2022-09-12 18:28 UTC, clopezh commented on src/components/referralform/referral.scss
> +        border-color: var(--rti-black) !important;
Should `!important` flag is needed?

2022-09-12 18:28 UTC, clopezh commented on src/components/referralform/referral.scss
>  .refferal-base
Please correct all the misspelled words
```suggestion
.referral-base 
```

2022-09-12 18:28 UTC, clopezh commented on src/routes.tsx
>              <Route strict exact path="/positions" component={OpenPosition} />
This is not needed anymore

2022-09-12 18:28 UTC, clopezh commented on src/views/referraledit/index.tsx
> +const ReferralEdit = () => {
```suggestion
const ReferralEdit = FunctionComponent<{props interface}>() => {
```

2022-09-12 18:28 UTC, clopezh commented on src/views/referraledit/index.tsx
> +    const {id}: any = useParams();
```suggestion
    const { id }: <create an interface> = useParams();
```

2022-10-11 16:01 UTC, clopezh requested changes
Hello @umeixueiroBC  there are some comments related with best practices, overall LGTM, but I recommend to clean the code and have the base (which is this PR) with the best practice.

2022-10-11 16:01 UTC, clopezh commented on src/views/referrals/ReferralCreateEdit.tsx
> +    const [referralData, setReferralData] = useState<any>();
avoid using any, please create interfaces to type the variable

2022-10-11 18:02 UTC, umeixueiroBC commented on src/components/button/Button.tsx
> +      </Stack>
Hi @clopezh, thanks for the review, I will doit for sure 😄

2022-10-11 18:04 UTC, umeixueiroBC commented on src/components/navbar/Navbar.tsx
> +                    <Box component="div" sx={ { display: {xs: 'none', sm: 'none', md: 'flex'} } }>
Hi @clopezh, thanks for the review, I will doit for sure 😄

2022-10-11 18:05 UTC, umeixueiroBC commented on src/components/navbar/Navbar.tsx
> +                    <Box component="div" sx={ { display: {xs: 'none', sm: 'none', md: 'flex'} } }>
Hi @clopezh, thanks for the review, I will doit for sure

2022-10-11 18:06 UTC, umeixueiroBC commented on src/components/navbar/Navbar.tsx
> +    //     title: 'Users',
Hi @clopezh, thanks for the review, I will do it for sure 😄

2022-10-11 18:23 UTC, umeixueiroBC commented on src/components/navbar/navbar.scss
> +  margin-right: 60px;
Hi @clopezh, thanks for the review, I will do it for sure 😄, I will use the standard 4 spaces (tab) indentation

2022-10-11 18:24 UTC, umeixueiroBC commented on src/components/referral/ReferralDataGrid.tsx
> +        field: "ID",
Yes, this because pass the ID to apply the action to the selected register.

2022-10-11 18:25 UTC, umeixueiroBC commented on src/components/referral/ReferralForm.tsx
> +    // }
Hi @clopezh, thanks for the review, I will do it for sure 😄

2022-10-11 18:36 UTC, umeixueiroBC commented on src/components/referral/index.tsx
> +export { default as ReferralDataGrid } from './ReferralDataGrid';
Hi @clopezh, thanks for the review, I will do it for sure 😄

2022-10-11 18:36 UTC, umeixueiroBC commented on src/views/bonus/index.tsx
> +export {default as MyBonus} from './bonus'
Hi @clopezh, thanks for the review, I will do it for sure 😄

2022-10-11 18:37 UTC, umeixueiroBC commented on src/views/referrals/ReferralCreateEdit.tsx
> +    const [referralData, setReferralData] = useState<any>();
Hi @clopezh, thanks for the review, I will do it for sure 😄

2022-10-13 14:36 UTC, umeixueiroBC commented on src/components/referral/ReferralDataGrid.tsx
> +        field: "ID",
Hi @clopezh, thanks for the review, you are right, I will change it according, thanks

2023-01-10 21:39 UTC, clopezh approved these changes

2023-01-10 21:39 UTC, merged